// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4zNThQl_Nknj9YDoz-ts9-W7ywd1CJEU',
    appId: '1:74006902989:web:f126722c166427030d9184',
    messagingSenderId: '74006902989',
    projectId: 'prestamosapp-67d35',
    authDomain: 'prestamosapp-67d35.firebaseapp.com',
    storageBucket: 'prestamosapp-67d35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DWcXPQcHNMsQF90Gd86gXTPa58Q1mdo',
    appId: '1:74006902989:android:cb65098c2a6e48bd0d9184',
    messagingSenderId: '74006902989',
    projectId: 'prestamosapp-67d35',
    storageBucket: 'prestamosapp-67d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_gWmPnHt7tmLBE6o_BGIdR0esoFX7e8',
    appId: '1:74006902989:ios:22d0c7bb89a1b7ee0d9184',
    messagingSenderId: '74006902989',
    projectId: 'prestamosapp-67d35',
    storageBucket: 'prestamosapp-67d35.appspot.com',
    androidClientId:
        '74006902989-30dkuora7l8hs8v91oa2cu7hukn9cbve.apps.googleusercontent.com',
    iosClientId:
        '74006902989-kjd4820oj9ekuptbppp98ks9pgid9k22.apps.googleusercontent.com',
    iosBundleId: 'com.example.prestamosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_gWmPnHt7tmLBE6o_BGIdR0esoFX7e8',
    appId: '1:74006902989:ios:a5f9705b298a7d200d9184',
    messagingSenderId: '74006902989',
    projectId: 'prestamosapp-67d35',
    storageBucket: 'prestamosapp-67d35.appspot.com',
    androidClientId:
        '74006902989-30dkuora7l8hs8v91oa2cu7hukn9cbve.apps.googleusercontent.com',
    iosClientId:
        '74006902989-va259s2hcl60idkvvfmahv88bn31pbr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.prestamosApp.RunnerTests',
  );
}
